name: Compile and test

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
      with:
        submodules: true
    - name: tests
      run: git submodule update; git submodule sync; mkdir -p build && cd build && cmake .. && make && cd tests && ./gpp_test
