name: Compile and test

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
      with:
        repository: sebbekarlsson/libjson
        path: extlib/.
    - name: make
      run: make
      #- name: install dependencies
      #run: sudo apt-get update -y && sudo apt-get install --yes libcmocka-dev libcmocka0
    - name: tests
      run: git submodule update; git submodule sync; cd tests && make && ./a.out
